version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-sqs-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-omcgcwroft00"
s3_prefix = "sam-app-sqs-lambda"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
