AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sqs-lambda

  Sample SAM Template for sqs-lambda

# DLQ stuff came from https://cloudkatha.com/how-to-configure-aws-sqs-dead-letter-queue-using-cloudformation/
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  MySqsQueueName:
    Type: String
    Description: Standard Queue Name
    Default: my-sqs-queue
  MyDeadLetterQueueName:
    Type: String
    Description: DLQ Queue Name
    Default: my-dead-letter-queue

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app_command_responder.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  MySQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app_event_responder.lambda_handler
      Runtime: python3.8
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn
            BatchSize: 10

  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      # commented because I didn't want to change the name
      # QueueName: !Ref MySourceQueueName
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MyDeadLetterQueue.Arn

        maxReceiveCount: 2

  MyDeadLetterQueue:
    Type: AWS::SQS::Queue
#    Properties:
#      QueueName: !Ref MyDeadLetterQueueName

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  SourceQueueURL:
    Description: URL of Source Queue
    Value: !Ref MySqsQueue
  SourceQueueARN:
    Description: ARN of source queue
    Value: !GetAtt MySqsQueue.Arn
  DeadLetterQueueURL:
    Description: URL of dead-letter queue
    Value: !Ref MyDeadLetterQueue
  DeadLetterQueueARN:
    Description: ARN of dead-letter queue
    Value: !GetAtt MyDeadLetterQueue.Arn